# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

-bash: |
  cat > .env <<EOF
  PRODUCT_SERVICE_BASE_URL=https://twt-prod-product-service.azurewebsites.net/
  INVENTORY_SERVICE_BASE_URL=https://twt-prod-inventory-service.azurewebsites.net/
  EOF
  displayName: 'Set up DB Connection'

-bash: |
  npm run build
  ls
  displayName: 'Build App'

- task: ArchiveFiles@2
  displayName: 'Archive dist'
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false
    
- task: CopyFiles@2
  displayName: 'copy files to :$(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'PublishBuildArtifacts: drop'
